SuperPrinting-war/src/fit5042/ass/mbeans/CustomerManagedBean.java
package fit5042.ass.mbeans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;

import javax.faces.context.FacesContext;
import javax.inject.Named;

import fit5042.ass.repository.CustomerRepository;
import fit5042.ass.repository.entities.Address;
import fit5042.ass.repository.entities.Customer;
import fit5042.ass.repository.entities.DataCommunicationCustomer;
import fit5042.ass.repository.entities.HealthCustomer;
import fit5042.ass.repository.entities.Contact;

/**
 * 
 * @author Yan
 *
 */

@Named(value = "customerManagedBean")
@SessionScoped
public class CustomerManagedBean implements Serializable{
	
	@EJB
	CustomerRepository customerRepository;

	public CustomerManagedBean() {
	}
	
    public List<Customer> getAllCustomers() {
        try {
        	List<Customer> customers = customerRepository.getAllCustomers();
            return customers;
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public List<DataCommunicationCustomer> getAllDcCustomers() {
        try {
        	List<DataCommunicationCustomer> customers = customerRepository.getAllDcCustomers();
            return customers;
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public List<HealthCustomer> getAllHeCustomers() {
        try {
        	List<HealthCustomer> customers = customerRepository.getAllHeCustomers();
            return customers;
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public void setCustomerList(List<Customer> customerList) {
    	try {
    		customerRepository.setCustomerList(customerList);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
	}
    
    public void addCustomer(fit5042.ass.customerControllers.Customer localCustomer) 
    {
    	Customer customer = convertCustomerToEntity(localCustomer);
        try {
        	customerRepository.addCustomer(customer);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void editCustomer(Customer customer)
    {
        try {
            String streetNumber = customer.getAddress().getStreetNumber();
            String streetAddress = customer.getAddress().getStreetAddress();
            String suburb = customer.getAddress().getSuburb();
            String state = customer.getAddress().getState();
            String postcode = customer.getAddress().getPostcode();
            
            Address address = customer.getAddress();
            address.setStreetNumber(streetNumber);
            address.setStreetAddress(streetAddress);
            address.setSuburb(suburb);
            address.setState(state);
            address.setPostcode(postcode);
            
            customer.setAddress(address);
            
            customerRepository.editCustomer(customer);
            
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("Customer has been updated succesfully"));
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void removeCustomer(int customerId) 
    {
        try {
        	customerRepository.removeCustomer(customerId);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public Customer searchCustomerById(int customerId)
    {
        try {
            return customerRepository.searchCustomerById(customerId);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public List<Customer> searchCustomerByUserid(int userid)
    {
        try {
            return customerRepository.searchCustomerByUserid(userid);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public List<Contact> getAllCustomerContacts() {
    	try {
            return customerRepository.getAllCustomerContacts();
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
		return null;
	}
    
    //...
    public List<Customer> searchCustomerByName(String name) {
    	try {
            return customerRepository.searchCustomerByName(name);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
		return null;
	}
    
    public List<Customer> searchCustomerByMultipleField(String field1, String value1, String field2, String value2) {
    	try {
            return customerRepository.searchCustomerByMultipleField(field1, value1, field2, value2);
        } catch (Exception ex) {
            Logger.getLogger(CustomerManagedBean.class.getName()).log(Level.SEVERE, null, ex);
        }
		return null;
	}
    
    private Customer convertCustomerToEntity(fit5042.ass.customerControllers.Customer localCustomer) {
    	
    	Customer customer = new Customer(); //entity
    	
        String streetNumber = localCustomer.getStreetNumber();
        String streetAddress = localCustomer.getStreetAddress();
        String suburb = localCustomer.getSuburb();
        String postcode = localCustomer.getPostcode();
        String state = localCustomer.getState();
        Address address = new Address(streetNumber, streetAddress, suburb, postcode, state);
        
        customer.setAddress(address);
        customer.setCustomerId(localCustomer.getCustomerId());
        customer.setName(localCustomer.getName());
        customer.setPhoneNumber(localCustomer.getPhoneNumber());
        customer.setEmail(localCustomer.getEmail());
        customer.setFax(localCustomer.getFax());
        customer.setDescription(localCustomer.getDescription());
        customer.setIndustryType(localCustomer.getIndustryType());
        customer.setUserid(localCustomer.getUserid());
        //customer.setCustomerContacts(localCustomer.getCustomerContacts());
        
        
        return customer;
    }

}

SuperPrinting-war/src/fit5042/ass/userControllers/UserController.java
package fit5042.ass.userControllers;

import javax.el.ELContext;
import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import fit5042.ass.userControllers.UserApplication;

/**
 * 
 * @author Yan
 *
 */

@Named(value = "userController")
@RequestScoped
public class UserController {

	private int id;
	private fit5042.ass.repository.entities.Users user;
	
	public UserController() {
		id = Integer.valueOf(FacesContext.getCurrentInstance()
                .getExternalContext()
                .getRequestParameterMap()
                .get("userID"));
        // Assign property based on the id provided 
        user = getUser();
    }

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	public fit5042.ass.repository.entities.Users getUser() {
        if (user == null) {
            ELContext context
                    = FacesContext.getCurrentInstance().getELContext();
            UserApplication userApplication
                    = (UserApplication) FacesContext.getCurrentInstance()
                            .getApplication()
                            .getELResolver()
                            .getValue(context, null, "userApplication");
            // -1 to userId to have positive user id
            return userApplication.getUsers().get(--id); 
        }
        return user;
    }
}

SuperPrinting-war/WebContent/users/addContact.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">
    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Add Customer Contact
                </div>
            </div>
            <div>
        <f:view>
            <h:form>
                <h1><h:outputText value="Create"/></h1>
                
                <table class="table table-bordered ">
                
                	<tr>
                        <td>
                            <h:outputLabel value="Name:" for="name" />
                        </td>
                        <td>
                            <h:inputText id="name" value="#{contact.name}"  required="true" 
                                         requiredMessage="Please enter the contact name!" pt:placeholder="###">
                           	</h:inputText>
                           	<br/>
                           	<h:message for="name" class="#{!name.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr>
                        <td>
                            <h:outputLabel value="Gender:" for="gender" />
                        </td>
                        <td>
                        <h:selectOneMenu value="#{contact.gender}" id="gender">
                        	<f:selectItem itemValue="#{null}" itemLabel="--select--" />
                        	<f:selectItem itemLabel = "male" itemValue = "male"/>
                        	<f:selectItem itemLabel = "female" itemValue = "female"/>
                        	<f:selectItem itemLabel = "prefer not to say" itemValue = "prefer not to say"/>
                        </h:selectOneMenu> 
                        </td>                       
                    </tr>                    
                    <tr>
                        <td>
                            <h:outputLabel value="Title:" for="title" />
                        </td>
                        <td>
                            <h:inputText id="title" value="#{contact.title}"  required="true" 
                                         requiredMessage="Please enter the contact title!" pt:placeholder="###">
                           	</h:inputText>
                           	<br/>
                           	<h:message for="title" class="#{!title.valid ? 'label label-warning' : 'none'}" />
                        </td> 
                    </tr>
                    
                    <tr>
                        <td>
                            <h:outputLabel value="Position:" for="position" />
                        </td>
                        <td>
                            <h:inputText id="position" value="#{contact.position}"  required="true" 
                                         requiredMessage="Please enter the contact position!" pt:placeholder="###">
                           	</h:inputText>
                           	<br/>
                           	<h:message for="position" class="#{!position.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr>
                        <td>
                            <h:outputLabel value="PhoneNumber:" for="phoneNumber"/>
                        </td>
                        <td>
                            <h:inputText id="phoneNumber" value="#{contact.phoneNumber}" size="10" required="true" 
                            			validatorMessage="Please enter a valid phone number "
                                         requiredMessage="Please enter the phone number!" pt:placeholder="0000000000">
                                <f:validateRegex pattern = "^\({0,1}((0|\+61)(2|4|3|7|8)){0,1}\){0,1}(\ |-){0,1}[0-9]{2}(\ |-){0,1}[0-9]{2}(\ |-){0,1}[0-9]{1}(\ |-){0,1}[0-9]{3}$"/>
                           	</h:inputText>
                           	<br/>
                           	<h:message for="phoneNumber" class="#{!phoneNumber.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr>
                        <td>
                            <h:outputLabel value="Email:" for="email" />
                        </td>
                        <td>
                            <h:inputText id="email" value="#{contact.email}" required="true" 
                                         requiredMessage="Please enter the email!" 
                                         validatorMessage="Please enter a valid email " 
                                         pt:placeholder="###@gmail.com">
                            	<f:validateRegex pattern = "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"/>
                           	</h:inputText>
                           	<br/>
                           	<h:message for="email" class="#{!email.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                          
                    <tr>
                        <td>
                            <h:outputLabel value="Birthdate: " for="birthdate" />
                        </td>
                        <td>
                            <h:inputText id="birthdate" value="#{contact.birthdate}" required="true" 
                                         requiredMessage="Please enter the birthdate!" >
                            	<f:convertDateTime pattern="yyyy-MM-dd" />
                           	</h:inputText>
                           	<br/>
                           	<h:message for="birthdate" class="#{!birthdate.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>                
                    
                     <tr>
                        <td width ="200">
                            <h:outputLabel value="Customer Name: " for="customer" />
                        </td>
                        <td>
                            <h:selectOneMenu  value="#{contact.customer}" id="customer" converter="customer" >
                            	<f:selectItem itemValue="#{null}" itemLabel="--select--" />
								<f:selectItems value="#{customerManagedBean.allCustomers}"
										var="c" itemLabel="#{c.name}" itemValue="#{c}" />
							</h:selectOneMenu >
                        </td>
                    </tr>
                    
                                       
                </table>
                
                <h:commandButton id="submit" value="Submit" action="#{addContact.addContact(contact)}" class="btn btn-primary" >
                </h:commandButton>
                <h:link id="close" value="Close" outcome="/faces/users/indexCustomer.xhtml"
						class="btn btn-primary" />
            	
            </h:form>
			
        </f:view>
            </div>
        </div>
       
    </h:body>
</html>

SuperPrinting-war/WebContent/users/addCustomer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough" 
      xmlns:a4j="http://richfaces.org/a4j">

    <h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <h:outputStylesheet library="css" name="style.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    <h:body>
        <div class="container">
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - Add Customer
                </div>
            </div>
            <div>
        <f:view>
            <h:form>
            
                <h1><h:outputText value="Create"/></h1>
                

                <table class="table table-bordered ">
                
                	<tr>
                        <td>
                            <h:outputLabel value="Name:" for="name" />
                        </td>
                        <td>
                            <h:inputText id="name" value="#{customer.name}"  required="true" 
                                         requiredMessage="Please enter the customer name!" pt:placeholder="###">
                           	</h:inputText>
                           	<br/>
                           	<h:message for="name" class="#{!name.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr>
                        <td>
                            <h:outputLabel value="PhoneNumber:" for="phoneNumber"/>
                        </td>
                        <td>
                            <h:inputText id="phoneNumber" value="#{customer.phoneNumber}" size="10" required="true" 
                            			validatorMessage="Please enter a valid phone number "
                                         requiredMessage="Please enter the phone number!" pt:placeholder="0000000000">
                                  <f:validateRegex pattern = "^\({0,1}((0|\+61)(2|4|3|7|8)){0,1}\){0,1}(\ |-){0,1}[0-9]{2}(\ |-){0,1}[0-9]{2}(\ |-){0,1}[0-9]{1}(\ |-){0,1}[0-9]{3}$"/>
                           	</h:inputText>
                           	<br/>
                           	<h:message for="phoneNumber" class="#{!phoneNumber.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr>
                        <td>
                            <h:outputLabel value="Email:" for="email" />
                        </td>
                        <td>
                            <h:inputText id="email" value="#{customer.email}" required="true" 
                                         requiredMessage="Please enter the email!" 
                                         validatorMessage="Please enter a valid email " 
                                         pt:placeholder="###@gmail.com">
                            	<f:validateRegex pattern = "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$"/>
                           	</h:inputText>
                           	<br/>
                           	<h:message for="email" class="#{!email.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                     <tr>
                        <td>
                            <h:outputLabel value="Fax:" for="fax" />
                        </td>
                        <td>
                            <h:inputText id="fax" value="#{customer.fax}" required="true" 
                                         requiredMessage="Please enter the fax!" 
                                         validatorMessage="Please enter a valid fax. " 
                                         pt:placeholder="+#######">
                            	<f:validateRegex pattern = "^\+?[0-9]{7,}$"/>
                           	</h:inputText>
                           	<br/>
                           	<h:message for="fax" class="#{!fax.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                     <tr>
                        <td>
                            <h:outputLabel value="Description: " for="description" />
                        </td>
                        <td>
                            <h:inputText id="description" value="#{customer.description}" required="true" 
                                         requiredMessage="Please enter the description!" pt:placeholder="***"/>
                        	<br/>
                            <h:message for="description" class="#{!description.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr>
                        <td>
                            <h:outputLabel value="IndustryType: " for="industryType" />
                        </td>
                        <td>
                            <h:selectOneMenu  value="#{customer.industryType}" id="industryType" >
								<f:selectItems value = "#{industrytypeManagedBean.typenames}"/>
							</h:selectOneMenu >
							<br/>
							<h:message for="industryType" class="#{!industryType.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                     <tr class="#{!streetNumber.valid ? 'has-error' : 'none'}">
                        <td width ="200">
                            <h:outputLabel value="StreetNumber: " for="streetNumber" />
                        </td>
                        <td>
                            <h:inputText id="streetNumber" value="#{customer.streetNumber}" 
                            			 required="true" requiredMessage="Please enter the street number!" 
                            			 validatorMessage="Please enter a street number between 1 and 1000" 
                            			 converterMessage="Please enter a number" pt:placeholder="900">
	                            <f:convertNumber integerOnly="true"/>
								<f:validateLongRange minimum="1" maximum="1000" /> 
							</h:inputText>
                            <br/>
                            <h:message for="streetNumber" class="#{!streetNumber.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    </tr>

                    <tr class="#{!streetAddress.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="streetAddress" for="streetAddress" />
                        </td>
                        <td>
                            <h:inputText id="streetAddress" value="#{customer.streetAddress}" 
                                         required="true" requiredMessage="Please enter the street address!" pt:placeholder="Dandenong Rd"/>
                            <br/>
                            <h:message for="streetAddress" class="#{!streetAddress.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr class="#{!suburb.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Suburb: " for="suburb" />
                        </td>
                        <td>
                            <h:inputText id="suburb" value="#{customer.suburb}"  required="true" 
                                         requiredMessage="Please enter the suburb!" pt:placeholder="Caulfield East"/>
                        	<br/>
                            <h:message for="suburb" class="#{!suburb.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr class="#{!state.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="State:"  for="state"/>
                        </td>
                        <td>
                            <h:inputText id="state" value="#{customer.state}" size="3" required="true" 
                                         requiredMessage="Please enter the state!" pt:placeholder="VIC"/>
                            <br/>
                            <h:message for="state" class="#{!state.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr class="#{!postcode.valid ? 'has-error' : 'none'}">
                        <td>
                            <h:outputLabel value="Postcode: " for="postcode" />
                        </td>
                        <td>
                            <h:inputText id="postcode" value="#{customer.postcode}" required="true" 
                                          requiredMessage="Please enter the postcode!" 
                                          validatorMessage="Please enter a postcode between 0200 and 4700" 
                                          converterMessage="Please enter a number" pt:placeholder="3145">
	                            <f:convertNumber integerOnly="true"/>
								<f:validateLongRange minimum="200" maximum="4700" /> 
							</h:inputText>
							<br/>
							<h:message for="postcode" class="#{!postcode.valid ? 'label label-warning' : 'none'}" />
                        </td>
                    
                    </tr>
                    
                    <tr>
                        <td width ="200">
                            <h:outputLabel value="User Id: " for="userid" />
                        </td>
                        <td valign="bottom">       
    						<h:outputText id="userid" value="#{authentication.user.id}"/>
                        </td>
                    </tr>
                    

                                       
                </table>
                
                <h:commandButton id="submit" value="Submit" action="#{addCustomer.addCustomer(customer)}" class="btn btn-primary" >
                	<f:actionListener binding="#{customer.setUserid(authentication.user.id)}" />
                </h:commandButton>
                <h:link id="close" value="Close" outcome="/faces/users/indexCustomer.xhtml"
						class="btn btn-primary" />
            	
            </h:form>
			
        </f:view>
            </div>
        </div>
       
    </h:body>
</html>

SuperPrinting-war/WebContent/users/detail.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
      
	<h:head>
        <h:outputStylesheet library="css" name="bootstrap.min.css"></h:outputStylesheet>
        <title>#{titleController.pageTitle}</title> 
    </h:head>
    
    <h:body>
        <div class="container">
        
            <div class="navbar navbar-inverse">
                <div class="navbar-brand">
                    #{titleController.pageTitle} - My information
                </div>
            </div>

              <h:form id="MyForm">
    
                <table class="table table-bordered ">
                   <tr>
                        <td width ="150" valign="top">Id:</td>
                        
                        <td valign="bottom">
                            <h:outputLabel id = "Id" >#{userApp.user.id}</h:outputLabel>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="150" valign="top">Name:</td>
                        
                        <td valign="bottom">
                            <h:outputLabel id = "Name" >#{userApp.user.username}</h:outputLabel>    
                        </td>
                    </tr>   
                    <tr>
                        <td width ="150" valign="top">Password:</td>
                        
                        <td valign="bottom">
                            <h:outputLabel id = "Password" >#{userApp.user.password}</h:outputLabel>    
                        </td>
                    </tr>
                    <tr>
                        <td width ="150" valign="top">Groupname:</td>
                        
                        <td valign="bottom">
                            <h:outputLabel id = "Groupname" >#{userApp.user.groupname}</h:outputLabel>    
                        </td>
                    </tr>          
                    
                 </table>   
				
				<div>	
				<h:commandButton action="/changePassword" value="Change Password" id="submit" class="btn btn-primary">
                          <f:param name="userID" value="1"/>
                    </h:commandButton>
 				&nbsp;&nbsp;&nbsp;&nbsp;	
                <h:commandButton id="close" value="Close" action="/faces/users/home.xhtml"
					class="btn btn-primary" />
				</div>   
                
            </h:form>
            
        </div>
    </h:body>

</html>